[build]
command = "npm install --legacy-peer-deps && ng run ecomrce-project-1:prerender"
functions="netlify/functions"
publish="dist/ecomrce-project-1/browser"

[[redirects]]
from="/*"
to="/index.html"
status=200
